### PR TITLE
Update Benchmarking Script

### PR DESCRIPTION
**Pull request by proteneer**
This PR:

1) Adds RBFE tests to the tests/benchmark.py file
2) the RBFE tests use a "simple charge handler" to avoid vendors having to import openeye
3) renames the misnamed smirnoff_1_1_0_recharge.py ff to the more appropriate smirnoff_1_1_0_sc.py

### CODE REVIEW

**Comment by proteneer** [comment]
```
dhfr-apo: N=23558 speed: 324.98ns/day dt: 1.5fs (ran 100000 steps in 39.89s)
hif2a-apo: N=8805 speed: 586.40ns/day dt: 1.5fs (ran 100000 steps in 22.11s)
hif2a-rbfe: N=8840 speed: 471.76ns/day dt: 1.5fs (ran 100000 steps in 27.48s)
solvent-apo: N=6282 speed: 728.33ns/day dt: 1.5fs (ran 100000 steps in 17.80s)
solvent-rbfe: N=6317 speed: 579.22ns/day dt: 1.5fs (ran 100000 steps in 22.38s)
```

**Comment by proteneer** [comment]
@maxentile let me know if this looks okay to merge - forgot to request one earlier.

**Review by maxentile — APPROVED** [review]
Looks great!

>renames the misnamed smirnoff_1_1_0_recharge.py ff to the more appropriate smirnoff_1_1_0_sc.py

Double-checked for other uses and I think you got them all. Could you add a comment where appropriate on the difference between `smirnoff_1_1_0_sc.py` and `smirnoff_1_1_0_ccc.py`?

**Comment by maxentile** [comment]
Also, those timing numbers are fantastic! 🏎️ 

This script will help us spot possible rbfe-specific performance regressions in the future, and keep track of possible future speed increases.

**Pull request merged**
