### PR TITLE
Thermodynamic Derivative

### PR DESCRIPTION
**Pull request by proteneer**
Not meant to be merged - playing around with Langevin piston via jax and thermodynamic derivatives

### CODE REVIEW

**Comment by proteneer** [comment]
Currently debugging an issue of derivatives of being extremely unstable - going to try the thermodynamic derivative.

**Comment by proteneer** [comment]
This also seems to be working for a simple 2d density fitting procedure.

**Comment by proteneer** [comment]
```epoch 0 loss 7.844915500821131 O -12.15508449917887
epoch 1 loss 6.8719058568320435 O -13.128094143167957
epoch 2 loss 5.184204110585318 O -14.815795889414682
epoch 3 loss 3.4989133808606674 O -16.501086619139333
epoch 4 loss 1.6973231977841188 O -18.30267680221588
epoch 5 loss 0.6251289012423484 O -20.62512890124235
epoch 6 loss 1.6608258839438932 O -18.339174116056107
epoch 7 loss 1.9370176439773736 O -21.937017643977374
epoch 8 loss 2.08414566612133 O -17.91585433387867
epoch 9 loss 1.3806760247014402 O -21.38067602470144
epoch 10 loss 1.9029151836914444 O -18.097084816308556
epoch 11 loss 1.0357621874230425 O -21.035762187423042
epoch 12 loss 1.623048087005234 O -18.376951912994766
epoch 13 loss 1.0935305755160378 O -21.093530575516038
epoch 14 loss 1.387431576287618 O -18.612568423712382
```

**Comment by proteneer** [comment]
The next really exciting test is to see if thermodynamic derivative of the free energy works!

**Comment by proteneer** [comment]
Results for a 2D LennardJones fluid, insertion of a single particle using exponential averaging as the free energy estimator is fairly promising:

```
epoch 0 loss 7.007412571893619 O 12.007412571893619
epoch 1 loss 4.882234589234168 O 9.882234589234168
epoch 2 loss 4.658818091122859 O 9.658818091122859
epoch 3 loss 3.796865931857118 O 8.796865931857118
epoch 4 loss 2.150909557974452 O 7.150909557974452
epoch 5 loss 1.69033834092198 O 6.69033834092198
epoch 6 loss 0.8050993926309822 O 5.805099392630982
epoch 7 loss 0.1695628044298223 O 5.169562804429822
epoch 8 loss 0.09635135259016181 O 5.096351352590162
epoch 9 loss 0.9491626203468009 O 4.050837379653199
epoch 10 loss 0.3584897807480747 O 4.641510219251925
epoch 11 loss 0.25178842394553236 O 5.251788423945532
```

**Comment by jchodera** [comment]
NICE

**Comment by proteneer** [comment]
Merging this as a reference/temporary code.

**Pull request merged**
