### PR TITLE
Host Guest Systems

### PR DESCRIPTION
**Pull request by proteneer**
Add examples for host-guest systems. Thanks @guoweiqi for providing the host-acd xml files.

### CODE REVIEW

**Comment by proteneer** [comment]
We should be able to start overfitting tests next week!

**Comment by proteneer** [comment]
Cyclodextrin host seems to now have stable derivatives w.r.t. charges! Now we can start work on the guests.

**Comment by proteneer** [comment]
Added code for merging host and guest system together. It's not perfect but it should be *correct*.

**Comment by proteneer** [comment]
The important code is this combiner code:

```python
def combiner(
    a_nrgs, b_nrgs,
    a_params, b_params,
    a_param_groups, b_param_groups,
    a_conf, b_conf,
    a_masses, b_masses):
    """
    Combine two systems into one.
    """

    num_a_atoms = len(a_masses)
    c_masses = np.concatenate([a_masses, b_masses])
    c_conf = np.concatenate([a_conf, b_conf])
    c_params = np.concatenate([a_params, b_params])
    c_param_groups = np.concatenate([a_param_groups, b_param_groups])

    a_nrgs.sort(key=str)
    b_nrgs.sort(key=str)

    c_nrgs = []
    for a, b in zip(a_nrgs, b_nrgs):
        a_name = a[0]
        a_args = a[1]
        b_name = b[0]
        b_args = b[1]
        print(a_name, b_name)
        assert a_name == b_name
        if a_name == custom_ops.HarmonicBond_f64:
            bond_idxs = np.concatenate([a_args[0], b_args[0] + num_a_atoms], axis=0)
            bond_param_idxs = np.concatenate([a_args[1], b_args[1] + len(a_params)], axis=0)
            c_nrgs.append(custom_ops.HarmonicBond_f64(bond_idxs, bond_param_idxs))
        elif a_name == custom_ops.HarmonicAngle_f64:
            angle_idxs = np.concatenate([a_args[0], b_args[0] + num_a_atoms], axis=0)
            angle_param_idxs = np.concatenate([a_args[1], b_args[1] + len(a_params)], axis=0)
            c_nrgs.append(custom_ops.HarmonicAngle_f64(angle_idxs, angle_param_idxs))
        elif a_name == custom_ops.PeriodicTorsion_f64:
            torsion_idxs = np.concatenate([a_args[0], b_args[0] + num_a_atoms], axis=0)
            torsion_param_idxs = np.concatenate([a_args[1], b_args[1] + len(a_params)], axis=0)
            c_nrgs.append(custom_ops.HarmonicAngle_f64(torsion_idxs, torsion_param_idxs))
        elif a_name == custom_ops.LennardJones_f64:
            lj_scale_matrix = np.ones(shape=(len(c_masses), len(c_masses)), dtype=np.float64)
            lj_scale_matrix[:num_a_atoms, :num_a_atoms] = a_args[0]
            lj_scale_matrix[num_a_atoms:, num_a_atoms:] = b_args[0]
            lj_param_idxs = np.concatenate([a_args[1], b_args[1] + num_a_atoms], axis=0)
            c_nrgs.append(custom_ops.LennardJones_f64(lj_scale_matrix, lj_param_idxs))
        elif a_name == custom_ops.Electrostatics_f64:
            es_scale_matrix = np.ones(shape=(len(c_masses), len(c_masses)), dtype=np.float64)
            es_scale_matrix[:num_a_atoms, :num_a_atoms] = a_args[0]
            es_scale_matrix[num_a_atoms:, num_a_atoms:] = b_args[0]
            es_param_idxs = np.concatenate([a_args[1], b_args[1] + num_a_atoms], axis=0)
            c_nrgs.append(custom_ops.Electrostatics_f64(es_scale_matrix, es_param_idxs))
    return c_nrgs, c_params, c_param_groups, c_conf, c_masses
```
@guoweiqi  I will probably need you to eyeball this logic as well to make sure it's correct.

**Comment by proteneer** [comment]
@guoweiqi The first host-guest system is now stable to run with.

**Comment by proteneer** [comment]
@guoweiqi if you pull this branch you should be able to run the notebook

**Comment by jchodera** [comment]
@proteneer : How does the explicit solvent simulation performance compare to OpenMM?

**Comment by proteneer** [comment]
It's atrocious because it would have to use the pure JAX backend since I haven't implemented periodic boxes/Ewald yet in the CUDA layer.

**Comment by proteneer** [comment]
So what's interesting is that the thermodynamic gradient is not agreeing with the analytic gradient (ran on a single trajectory) for a vast majority of cases. 

```
[-0.02531424 -0.00793294 -0.00754284  0.00306674 -0.05236083 -0.04145655
  0.          0.          0.          0.        ] analytic
[-0.00366282  0.00616603  0.0072869  -0.00330846  0.26365962  0.11145437
  0.          0.          0.          0.        ] thermodynamic
[ 0.14469402 -0.77726875 -0.96606883 -1.07882057 -5.0354362  -2.68846247
         nan         nan         nan         nan] thermodynamic/analytic
```

I'm not really sure what to make of this.

**Comment by proteneer** [comment]
Results from another run comparing the charges: grad_analytic, grad_thermo, grad_thermo/grad_analytic

```
[ 147.09095761  469.17928885  700.87124498  156.4797289   367.15172093
  621.33738611 -249.76998338   71.25319495  141.64720423  182.32083477
 -550.41599817  414.15891243   67.00764589  285.12370558  281.64616857
  677.21127126  124.90417714   76.45999736  102.84990207  197.73575447
   92.37786066   46.08474513  339.85583247  633.77222223  139.67643909
  371.11074211  613.61362773 -261.36662236   63.93346667  102.65361314]
[  6619.2559592   58483.52603971 104498.30104795  21381.7685624
  58616.63876115 100154.67367918 -46418.48200182  10121.12771089
  20986.61458945  28461.98914098 -94448.40964489  74437.07333794
  17524.9989375   39640.02668394  44618.81516039  91450.63993769
  19393.4145547   16884.02340495  21027.18088467  28126.34872661
   7609.65682339   6520.64643941  57540.99665729 104401.03761162
  19328.8815626   57467.39867337 100235.79028782 -45022.87694333
   5231.84032951  13400.82527447]
[  45.00110725  124.65069842  149.09771487  136.64241824  159.6523601
  161.19209292  185.84491768  142.04454577  148.16116353  156.1093617
  171.59459383  179.73070506  261.53730229  139.02746741  158.42152367
  135.0400441   155.26634096  220.82165824  204.44531751  142.24209882
   82.37533073  141.49251386  169.31001666  164.72958888  138.38326413
  154.85242585  163.35326622  172.25947421   81.83257693  130.54411691
  147.5253048   171.24718684  135.97073795   73.68245357  184.77339725
  148.20681142  173.15679581  179.60058856  110.4182122   157.38688481
  257.71421977 -139.74339929  167.42679295  167.377379    167.86662642
  169.20077317  168.6635623   167.15144992  166.62134789  165.5151363
  167.67438878  166.74249901  166.68125861  170.0740164   184.89483901
  159.01418595  167.57791344  166.53006133  150.89189173  166.21407944
  162.22063308  141.20545278  185.34472585  163.37326693  166.79050797
  160.57357605  165.30938904  167.13715673  166.35854817  156.46201316
  161.35503149  163.83025859  165.31922672  166.93279507  166.2838613
  164.5144678   165.64898267  164.54060168  166.52613392  162.38583358
  159.9976588   163.24732817  163.05611263  116.44864809  126.29832422
  158.46733765  160.7637826   158.88438789  165.09854247  164.96475911
  166.52515815  154.38735726  159.84346284  164.0957821   167.70683342
  164.75775637  161.99696703  160.83796318  160.72883346  160.28052514]
```

It's interesting to note that they're pretty similar but there are sign differences for one of the terms.

**Comment by proteneer** [comment]
I'm going to merge this in today before it gets too out of control - I"m not really happy with the design of the classes as is but at least the tests are passing.

**Comment by proteneer** [comment]
One of the tests I want to run is a comparison of the fitting results between the thermodynamic vs analytic derivatives and see which one can 1) overfit better and 2) generalize better

**Comment by proteneer** [comment]
Merging this in! Results look pretty interesting

**Pull request merged**
