### PR TITLE
Fixes failing nightly test

### PR DESCRIPTION
**Pull request by badisa**

### CODE REVIEW

**Review by jkausrelay — APPROVED** [review]

**Review by maxentile — APPROVED** [review]

**Comment by badisa** [comment]
Just waiting for this to finish: https://gitlab.com/relaytx/physics-platform/timemachine/-/jobs/2413454705

@jkausrelay @maxentile do we need the smc example test to run all of freesolv?

**Comment by jkausrelay** [comment]
@badisa It should just run on the first 10 molecules.

**Comment by maxentile** [comment]
Based on local testing this nightly test was intended to take [under an hour](https://github.com/proteneer/timemachine/blob/3dc38a399f0c9c743e9f3b23552874ad308361ff/tests/test_examples.py#L113-L119) -- if significantly longer, `n_mols` should be reduced further!

**Comment by badisa** [comment]
> @badisa It should just run on the first 10 molecules.

You are correct, sorry had missed that. 

> Based on local testing this nightly test was intended to take [under an hour](https://github.com/proteneer/timemachine/blob/3dc38a399f0c9c743e9f3b23552874ad308361ff/tests/test_examples.py#L113-L119) -- if significantly longer, n_mols should be reduced further!

Looks like right now it takes about 2 hours (6977 seconds)

**Comment by badisa** [comment]
Reduces the number of mols to 2 in the example test, that way it is only ~20 minutes rather than 2 hours.  Because the nightly tests ended up taking longer than 3 hours which is the current CI limit (though we could increase that).

**Comment by jkausrelay** [comment]
@badisa LGTM!

**Review by maxentile — APPROVED** [review]

**Comment by badisa** [comment]
Will merge once this passes successfully: https://gitlab.com/relaytx/physics-platform/timemachine/-/jobs/2414325220

**Comment by badisa** [comment]
@maxentile `test_vacuum_importance_sampling` is still failing. I have been trying to figure out how to fix it, but doesn't seem straight forward. Would you mind taking a look, it seems like this is the change that triggered it: https://github.com/proteneer/timemachine/commit/c1b564dafe4680563630aaf813f1463e63647a58#diff-6dfe06f71bc63005db1510d4317989dfc3706552e1225b8582cc3dab805b783aR401

**Pull request merged**
