### PR TITLE
[WIP] Thermodynamic derivative, PBC support, Reaction Fields, and Neighborlists

### PR DESCRIPTION
**Pull request by proteneer**
Here comes another 10,000 line PR. More details to come...

This PR:
- [x] Implements the Thermodynamic Derivative by moving dU/dp into inference mode calculations.
- [x] Implements rf electrostatics under an erfc
- [x] Implements rectangular PBCs
- [x] Refactored Integrator class
- [x] Implemented Observable class
- [x] Refactored Context class
- [x] Rename Gradient->Potential, firms the signature of U(x,params, theta, lambda) -> scalar
- [x] Implements a Bound Potential that's semantically equivalent to applying std::bind to a Potential with parameters
- [x] Remove GB parameters from smirnoff_1_1_0_ccc.py
- [x] Implemented Hydration Free Energy training protocol
- [x] Speed up LJ by 5x via eps trick for tip3p waters. Need to redo this later.
- [x] Neighborlist code

Playground tests for the thermodynamic derivative:
- [x] Analytical particle in a box
- [x] Density fitting for a 2D lennard jones system
- [x] LennardJones 2D particle insertion via zwanzig's / exp_avg
- [x] TI estimator for an explicit solvent hydration free energy system, optimizing LJ sigmas via thermodynamic integration

### CODE REVIEW

**Comment by proteneer** [comment]
Optimizing LJ sig for hydration

```
dG pred -197.8141522082091 dG expected -150
dG pred -194.1848396643517 dG expected -150
dG pred -189.6457531267849 dG expected -150
dG pred -186.92522654671373 dG expected -150
dG pred -183.99411252079207 dG expected -150
dG pred -181.89681835607794 dG expected -150
dG pred -177.491691622748 dG expected -150
dG pred -175.99442665126293 dG expected -150
dG pred -172.6103093863446 dG expected -150
dG pred -170.30434672368767 dG expected -150
dG pred -166.80351164041252 dG expected -150
dG pred -165.4985420686885 dG expected -150
dG pred -162.4049710273327 dG expected -150
dG pred -161.20804813223063 dG expected -150
dG pred -158.20652548616394 dG expected -150
dG pred -156.4410336519895 dG expected -150
dG pred -155.53345117913193 dG expected -150
dG pred -153.17867353144237 dG expected -150
dG pred -150.85147098579296 dG expected -150
dG pred -148.8548184883771 dG expected -150
dG pred -150.77634290493717 dG expected -150
dG pred -147.78233542657372 dG expected -150
dG pred -150.98260359222638 dG expected -150
dG pred -149.07052527913 dG expected -150
```

**Comment by proteneer** [comment]
On 23k water system, TIP3P

The current RF implementation is now about 346 ns/day, with full computation of du/dp, du/dl via 4D decoupling, u, and a full neighborlist rebuild on *every* step. This can be further optimized by another 30-40% without too much difficulty.

In contrast, the OpenMM implementation is currently 697ns/day (but for DHFR). I'm tempted to declare this good enough to start the next round training via thermodynamic derivatives. Maybe host-guest?

**Comment by jchodera** [comment]
> On 23k water system, TIP3P
> The current RF implementation is now about 346 ns/day

*NICE*

**Comment by jchodera** [comment]
[This host-guest dataset](https://doi.org/10.1021/acs.jpcb.5b04262) has been used to improve force field parameters previously, and may be an excellent starting point.

**Comment by proteneer** [comment]
Note to self: doing only forces for nonbonded calculations on 23k water particles drops 496us to 313us per step

**Comment by proteneer** [comment]
This will be ready for merging soonish

**Comment by proteneer** [comment]
Ported over the hilbert sorting entirely to the GPU, adding CUB as an extra header-only dependency. Thanks to Scott Le Grand for the tip. We needed an extra 256^3*4 bytes of RAM (66MB) to do this. However, this allows us to build more compact/efficient neighborlist since we don't need to worry about particle drift in between.

**Comment by proteneer** [comment]
First set of tests passed!

**Comment by proteneer** [comment]
full profiling results:

````
                   0.43%  406.46us         1  406.46us  406.46us  406.46us  void k_nonbonded<float>(int, double const *, double const *, double const *, double, int const *, double, double, int const *, unsigned int const *, __int64*, double*, double*, double*)
                    0.19%  181.76us         1  181.76us  181.76us  181.76us  void k_find_blocks_with_ixns<float>(int, double const *, double const *, double const *, double const *, unsigned int*, int*, unsigned int*, unsigned int*, double)
                    0.12%  113.98us         2  56.992us  56.768us  57.216us  void k_reduce_buffer<double>(int, double*, double*)
                    0.10%  98.400us         5  19.680us  19.136us  21.184us  void cub::RadixSortScanBinsKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, int>(unsigned int*, int)
                    0.06%  59.712us         3  19.904us  15.328us  29.056us  void cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, unsigned int, int>(cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, unsigned int, int>*, bool=1 const *, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, unsigned int, int>**, bool=0*, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, unsigned int, int>**, int, int, cub::GridEvenShare<cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, unsigned int, int>**>)
                    0.04%  36.576us         2  18.288us  5.8560us  30.720us  void cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, unsigned int, int>(cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, unsigned int, int>*, bool=0 const *, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, unsigned int, int>**, bool=0*, cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, unsigned int, int>**, int, int, cub::GridEvenShare<cub::DeviceRadixSortDownsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, unsigned int, int>**>)
                    0.02%  23.520us         3  7.8400us  6.3680us  10.752us  void cub::DeviceRadixSortUpsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=1, bool=0, unsigned int, int>(cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, bool=1*, cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, int, int, cub::GridEvenShare<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *>)
                    0.02%  22.944us         1  22.944us  22.944us  22.944us  k_find_block_bounds(int, int, int, double const *, double const *, double*, double*)
                    0.02%  19.200us        11  1.7450us  1.3120us  4.2240us  [CUDA memset]
                    0.02%  16.063us         2  8.0310us  6.2720us  9.7910us  void cub::DeviceRadixSortUpsweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700, bool=0, bool=0, unsigned int, int>(cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, bool=0*, cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *, int, int, cub::GridEvenShare<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>::Policy700 const *>)
                    0.01%  13.216us         1  13.216us  13.216us  13.216us  k_compact_trim_atoms(int, int, unsigned int*, unsigned int*, int*, unsigned int*)
                    0.01%  11.360us         2  5.6800us  5.5040us  5.8560us  void k_permute<double>(int, unsigned int const *, double const *, double*)
                    0.01%  10.880us         1  10.880us  10.880us  10.880us  k_coords_to_kv(int, double const *, double const *, unsigned int const *, unsigned int*, unsigned int*)
                    0.01%  6.8160us         1  6.8160us  6.8160us  6.8160us  void k_nonbonded_exclusions<float>(int, double const *, double const *, double const *, double, int const *, int const *, double const *, double, double, __int64*, double*, double*, double*)
                    0.01%  6.1750us         1  6.1750us  6.1750us  6.1750us  void k_inv_permute_accum<__int64>(int, unsigned int const *, __int64 const *, __int64*)
                    0.01%  6.0160us         1  6.0160us  6.0160us  6.0160us  void k_inv_permute_accum<double>(int, unsigned int const *, double const *, double*)
                    0.00%  3.0720us         1  3.0720us  3.0720us  3.0720us  void k_permute<int>(int, unsigned int const *, int const *, int*)
```

There's another 150us to be saved if we optimize the k_nonbonded kernels for *only* force computations.

**Comment by proteneer** [comment]
I'm going to try and get this merged before I start the serious optimizations, currently @ 1.5fs its running at 100 ns/day with a 10A cutoff. But it will be very straightforward to 2x to 3x this since:

1. We're rebuilding the neighborlist on every step (16%) - we may keep this still to avoid having to deal with padding
2. We're rebuilding the Hilbert curve on every step (16%) - this can be changed to once every 10 steps
3. We're computing du/dp, du/dl, u on every step (25%) - we only collect these maybe once every 10-100 steps in the *worst* case
4. We're computing the distance in 4D - this will be deferred until later since we need to do a block wise decomp of the nonbonded kernel and it makes the neighborlist tricky.

**Comment by proteneer** [comment]
Some fun derivatives for apo DHFR in explicit solvent :)
```
Delta 68.35414481163025
ns/day 94.80039605290254
<timemachine.lib.potentials.HarmonicBond object at 0x7f1e059bd0f0> (16569, 2)
[[ 4.58176236e-06 -1.23287099e+02]
 [ 2.60144091e-06  1.52500685e+02]
 [ 5.02766768e-06 -2.79234461e+02]
 ...
 [ 3.81293829e-06 -5.30963269e+01]
 [ 2.90394129e-06 -7.32308666e+01]
 [ 2.97903884e-06 -6.52099271e+01]]
<timemachine.lib.potentials.HarmonicAngle object at 0x7f1e059bd278> (11584, 2)
[[ 2.53635386e-03  5.27106738e+00]
 [ 1.77421101e-03  1.45452526e+01]
 [ 2.27194014e-03  2.80970500e+01]
 ...
 [ 1.47703054e-03  1.18816983e+00]
 [ 1.71643237e-03 -6.96438658e-01]
 [ 1.59397043e-03  1.96945788e-01]]
<timemachine.lib.potentials.PeriodicTorsion object at 0x7f1e059ba630> (7538, 3)
[[  0.34535432  -0.22532727   0.32663266]
 [  0.4446846   -0.28046661  -0.18251235]
 [  0.40242334  -0.26767835  -0.95466212]
 ...
 [  0.19149643   1.54100062  -5.42927217]
 [  0.39130327  -2.83976972  -7.74748228]
 [  0.05930158   6.82084571 -34.91545912]]
<timemachine.lib.potentials.Nonbonded object at 0x7f1e059ba668> (23558, 3)
[[-24.37837474 667.85212515   9.3983859 ]
 [-29.38370295  53.54798835   2.37811676]
 [-23.25798118   1.8202396   -7.32698411]
 ...
 [  1.0298803  138.26546087  -2.91019905]
 [  0.82967762   0.           0.        ]
 [  0.780142     0.           0.        ]]
```

**Comment by jchodera** [comment]
Nice!

**Comment by proteneer** [comment]
This new nblist results in roughly a 6x speedup on freesolv.  time per mol went from 570 seconds -> 95 seconds!

**Comment by proteneer** [comment]
Merging this.

**Comment by jchodera** [comment]
Nice!

**Pull request merged**
