### PR TITLE
Fix nightly test

### PR DESCRIPTION
**Pull request by mcwitt**
Fixes a missed update from #961 causing `test_rbfe_edge_list_hif2a` to fail (and breaking `run_edge_and_save_results`)

### CODE REVIEW

**Review by maxentile — APPROVED** [review]

**Comment by badisa** [comment]
Does this need to be changed in the example as well? https://github.com/proteneer/timemachine/blob/master/examples/relative_free_energy.py#L48

**Comment by mcwitt** [comment]
> Does this need to be changed in the example as well?

Yes, good catch. Updated in https://github.com/proteneer/timemachine/pull/962/commits/de05a2e24033bb1d34d0cf501f0ea577eb80b390.

**Comment by badisa** [comment]
> > Does this need to be changed in the example as well?
> 
> Yes, good catch. Updated in [de05a2e](https://github.com/proteneer/timemachine/commit/de05a2e24033bb1d34d0cf501f0ea577eb80b390).

Can you run the nightly tests against this branch to make sure we didn't miss anything else?

**Comment by mcwitt** [comment]
> Can you run the nightly tests against this branch to make sure we didn't miss anything else?

@badisa I did this already locally, but will kick off a CI run as well to be sure.

**Comment by badisa** [comment]
> > Can you run the nightly tests against this branch to make sure we didn't miss anything else?
> 
> @badisa I did this already locally, but will kick off a CI run as well to be sure. (The `relative_free_energy.py` example seems untested)

Ah nevermind then. Had mistaken it for the rbfe edge list.

**Review by badisa — APPROVED** [review]

**Comment by mcwitt** [comment]
Pipeline here: https://gitlab.com/relaytx/physics-platform/timemachine/-/pipelines/785731103

**Pull request merged**
