### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by proteneer**
AHFE/RHFE - mainly for pedagogical purposes, not for production.

### CODE REVIEW

**Comment by proteneer** [comment]
(we may or may not merge this)

**Comment by maxentile** [comment]
Thank you and @schmolly for walking through this with me! I will be a bit delayed with my review, aiming for ~Monday.

**Comment by proteneer** [comment]
Thanks for the comments - did you also want to do a pass over the RHFE examples?

**Review by maxentile — APPROVED** [review]
Looks great! I committed some line comments and a readme to capture some of the additional context you provided in our walkthrough on Friday, but hopefully my edits didn't change any of the functionality

**Pull request merged**
