### PR TITLE
Initial commit of the bonded Alchemical merge algorithm for Chuan to …

### PR DESCRIPTION
**Pull request by proteneer**
…scaffold off of.

### CODE REVIEW

**Comment by proteneer** [comment]
@PatWalters @bp-kelley if you guys have any better ideas on how the hell to do this please let me know.

**Comment by proteneer** [comment]
TL;DR is that this takes two molecules with a common core, and different R-groups R_A and R_B, and figures out how build an alchemical "hybrid". Note that we can't just do rdkit.CombineMols since the resulting molecule will be un-parameterizable due to the system, so we need to parameterize, then merge and do the interpolation.

**Comment by bp-kelley** [comment]
@proteneer Going to need a bit more guidance on this.  Could we iterate on a Jupyter notebook until we have something more concrete?

**Comment by proteneer** [comment]
stale

**Pull request closed without merging**
