### PR TITLE
Initial working version of RBFE

### PR DESCRIPTION
**Pull request by proteneer**
The new lambda mixing scheme is extremely well behaved, and still guarantees us that du/dlambda is analytically zero at endpoints:

lambda_du_dls

### CODE REVIEW

**Comment by jchodera** [comment]
Aren't those plots really problematic? You have <dU/dlambda> going from near zero at lambda = 0.8 to a huge positive number at 0.9.

**Comment by proteneer** [comment]
Is the concern of the excessive curvature?

1) This is with a garbage forcefield
2) Its mainly testing the stability of each individual lambda window.
3) We're may switch to NEQ anyways for production.
4) This is ring opening closing

Before we were seeing much worse behavior at the endpoints.

**Comment by proteneer** [comment]
Some example TI boxplots:

image

**Comment by proteneer** [comment]
```
pred_dG -6.8811234411511055

pred_dG -6.82703367567402

pred_dG -8.006304683333344

pred_dG -6.605760127383768

pred_dG -5.223329658410833

pred_dG -5.774490630119507

pred_dG -6.919988772780828

pred_dG -6.041870706793487

pred_dG -5.817150627240909

pred_dG -6.068451876538547

pred_dG -6.108679820318983

pred_dG -5.8264946636384085

pred_dG -5.2809853019067265

pred_dG -6.774918588812

pred_dG -6.796274599011355

pred_dG -5.0354089470840755

pred_dG -5.7445663498921

pred_dG -6.408920202691581
```

**Pull request merged**
