### PR TITLE
Templates langevin integrator to use floats by default

### PR DESCRIPTION
**Pull request by badisa**
* Matches the approach done for the MonteCarloBarostat in https://github.com/proteneer/timemachine/pull/1101
* Defaults to float to reduce memory usage and gain a ~5% performance improvement
* Did some basic investigation of increasing the batch size of the noise and it didn't seem to have any impact. 

# Benchmarks
Cuda Arch 8.6
Nvidia A10

## Current
```
dhfr-apo: N=23558 speed: 708.99ns/day dt: 2.5fs (ran 100000 steps in 30.47s)
dhfr-apo-barostat-interval-25: N=23558 speed: 637.04ns/day dt: 2.5fs (ran 100000 steps in 33.91s)
hif2a-apo: N=8805 speed: 1235.90ns/day dt: 2.5fs (ran 100000 steps in 17.48s)
hif2a-apo-barostat-interval-25: N=8805 speed: 1050.07ns/day dt: 2.5fs (ran 100000 steps in 20.57s)
hif2a-rbfe-barostat-interval-15: N=8840 speed: 784.25ns/day dt: 2.5fs (ran 100000 steps in 27.55s)
hif2a-rbfe-local: N=8840 speed: 1376.63ns/day dt: 2.5fs (ran 100000 steps in 15.69s)
solvent-apo: N=6282 speed: 1510.94ns/day dt: 2.5fs (ran 100000 steps in 14.30s)
solvent-apo-barostat-interval-25: N=6282 speed: 1347.81ns/day dt: 2.5fs (ran 100000 steps in 16.03s)
solvent-rbfe-barostat-interval-15: N=6317 speed: 1027.39ns/day dt: 2.5fs (ran 100000 steps in 21.03s)
solvent-rbfe-local: N=6317 speed: 1470.29ns/day dt: 2.5fs (ran 100000 steps in 14.70s)
```

## Floating point change
A 2-5% speed up. The difference is made by generating noise in float rather than doubles, the other changes are simply for consistency.

```
dhfr-apo: N=23558 speed: 744.85ns/day dt: 2.5fs (ran 100000 steps in 29.00s)
dhfr-apo-barostat-interval-25: N=23558 speed: 666.69ns/day dt: 2.5fs (ran 100000 steps in 32.40s)
hif2a-apo: N=8805 speed: 1265.93ns/day dt: 2.5fs (ran 100000 steps in 17.07s)
hif2a-apo-barostat-interval-25: N=8805 speed: 1078.83ns/day dt: 2.5fs (ran 100000 steps in 20.02s)
hif2a-rbfe-barostat-interval-15: N=8840 speed: 792.45ns/day dt: 2.5fs (ran 100000 steps in 27.26s)
hif2a-rbfe-local: N=8840 speed: 1461.39ns/day dt: 2.5fs (ran 100000 steps in 14.78s)
solvent-apo: N=6282 speed: 1545.76ns/day dt: 2.5fs (ran 100000 steps in 13.98s)
solvent-apo-barostat-interval-25: N=6282 speed: 1352.84ns/day dt: 2.5fs (ran 100000 steps in 15.97s)
solvent-rbfe-barostat-interval-15: N=6317 speed: 1051.67ns/day dt: 2.5fs (ran 100000 steps in 20.54s)
solvent-rbfe-local: N=6317 speed: 1516.41ns/day dt: 2.5fs (ran 100000 steps in 14.25s)
```

# Kernel timings
DHFR apo
Cuda Arch 8.6
Nvidia A4000

## Double Noise
```
CUDA Kernel Statistics:

 Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name                                                
 --------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
     63.2    1,380,105,021      4,000  345,026.3  344,640.0   302,976   374,336      8,122.6  void k_nonbonded_unified<float, (int)256, (bool)0, (bool)1, (bool)0>(int, int, const unsigned int *…
      9.3      202,118,565        790  255,846.3  256,303.5   215,967   279,135      8,206.3  void k_find_blocks_with_ixns<float, (bool)1>(int, int, int, const unsigned int *, const unsigned in…
      5.2      113,257,835        400  283,144.6  283,023.5   251,776   303,584      6,400.8  void gen_sequenced<curandStateXORWOW, double2, normal_args_double_st, &curand_normal_scaled2_double…
      3.8       83,384,576      4,160   20,044.4   20,895.0     8,320    32,704      2,447.8  void k_nonbonded_pair_list<float, (bool)1>(int, const double *, const double *, const double *, con…
      3.1       67,901,188      4,160   16,322.4   16,672.0     4,928    51,424      2,597.2  void k_harmonic_angle<float, (int)3>(int, const double *, const double *, const int *, unsigned lon…
      3.0       65,522,446      4,160   15,750.6   15,776.0     5,216    51,680      2,617.5  void k_periodic_torsion<float, (int)3>(int, const double *, const double *, const int *, unsigned l…
      2.6       56,001,152        160  350,007.2  350,768.0   311,808   362,047      7,316.4  void k_nonbonded_unified<float, (int)256, (bool)1, (bool)0, (bool)0>(int, int, const unsigned int *…
      2.5       55,041,703      4,160   13,231.2   13,568.0     3,649    48,832      3,361.9  void k_harmonic_bond<float>(int, const double *, const double *, const int *, unsigned long long *,…
      2.0       43,073,666      4,118   10,459.9   11,023.5     4,384    24,065      3,426.2  void k_check_rebuild_coords_and_box_gather<float>(int, const unsigned int *, const double *, const …
      1.8       38,877,266      4,000    9,719.3    9,472.0     7,648    13,920      1,037.4  void k_update_forward_baoab<double, (int)3>(int, T1, const unsigned int *, const T1 *, const T1 *, …
      1.2       27,200,018      4,160    6,538.5    6,400.0     4,160    19,136        764.9  void k_gather_coords_and_params<double, (int)3, (int)4>(int, const unsigned int *, const T1 *, cons…
      1.0       21,186,226      4,000    5,296.6    5,312.0     4,288    16,544        372.2  void k_scatter_accum<unsigned long long, (int)3>(int, const unsigned int *, const T1 *, T1 *)       
      0.6       12,026,718        790   15,223.7   15,360.0    11,904    29,408      1,139.9  k_compact_trim_atoms(int, int, unsigned int *, unsigned int *, int *, unsigned int *)               
      0.3        7,262,304      1,120    6,484.2    5,584.0     3,136    18,720      3,512.7  void k_accumulate_energy<(unsigned int)512>(int, const __int128 *, __int128 *)                      
      0.3        5,970,876        790    7,558.1    7,520.0     6,720    11,233        234.2  void k_find_block_bounds<float>(int, int, const unsigned int *, const double *, const double *, T1 …
      0.1        2,212,055        168   13,167.0   13,184.5    10,976    15,040        745.1  void cub::DeviceRadixSortOnesweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>…
      0.0          741,340         80    9,266.8    9,872.0     6,304    11,264      1,310.3  void k_decide_move<float>(int, bool, int, double, double, const T1 *, T1 *, double *, const __int12…
      0.0          705,600         42   16,800.0   16,992.0     6,720    23,232      3,901.4  k_coords_to_kv_gather(int, const unsigned int *, const double *, const double *, const unsigned int…
      0.0          672,737         80    8,409.2    8,416.0     7,360     9,248        245.3  void k_find_group_centroids<float>(int, const double *, const int *, const int *, unsigned long lon…
      0.0          573,210         80    7,165.1    7,168.0     6,495     7,487        145.0  void k_rescale_positions<float>(int, double *, const T1 *, const double *, double *, const int *, c…
      0.0          431,007          3  143,669.0  137,824.0   137,759   155,424     10,180.2  void generate_seed_pseudo<rng_config<curandStateXORWOW, (curandOrdering)101>>(unsigned long long, u…
      0.0          207,391         80    2,592.4    2,560.0     2,463     3,008        110.0  void k_setup_barostat_move<float>(bool, const T1 *, double *, T1 *, double *, T1 *)                 
      0.0          200,194         42    4,766.5    4,416.5     3,680    12,640      1,359.2  void cub::DeviceRadixSortHistogramKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int…
      0.0          110,718         42    2,636.1    2,576.0     1,984     3,072        219.4  void cub::DeviceRadixSortExclusiveSumKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, …
      0.0           17,536          8    2,192.0    2,128.0     1,728     2,688        289.8  k_arange(int, unsigned int *, unsigned int)                                                         
      0.0            2,304          1    2,304.0    2,304.0     2,304     2,304          0.0  void gen_sequenced<curandStateXORWOW, float, int, &curand_uniform_noargs<curandStateXORWOW>, rng_co…
```

## Float Noise
```
CUDA Kernel Statistics:

 Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name                                                
 --------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
     67.5    1,400,289,288      4,000  350,072.3  348,863.5   303,872   398,560      8,433.4  void k_nonbonded_unified<float, (int)256, (bool)0, (bool)1, (bool)0>(int, int, const unsigned int *…
      9.8      203,762,603        785  259,570.2  260,032.0   217,664   286,880      8,578.9  void k_find_blocks_with_ixns<float, (bool)1>(int, int, int, const unsigned int *, const unsigned in…
      4.1       84,182,135      4,160   20,236.1   21,024.0     7,969    31,359      2,543.4  void k_nonbonded_pair_list<float, (bool)1>(int, const double *, const double *, const double *, con…
      3.0       63,245,947      4,160   15,203.4   15,392.0     4,640    26,912      2,267.1  void k_harmonic_angle<float, (int)3>(int, const double *, const double *, const int *, unsigned lon…
      2.9       60,554,953      4,160   14,556.5   14,720.0     5,377    27,648      2,542.8  void k_periodic_torsion<float, (int)3>(int, const double *, const double *, const int *, unsigned l…
      2.7       56,887,622        160  355,547.6  355,983.0   311,296   380,831      8,552.6  void k_nonbonded_unified<float, (int)256, (bool)1, (bool)0, (bool)0>(int, int, const unsigned int *…
      2.4       49,622,601      4,160   11,928.5   12,032.0     3,680    26,080      2,881.7  void k_harmonic_bond<float>(int, const double *, const double *, const int *, unsigned long long *,…
      1.8       37,725,705      4,118    9,161.2    8,000.0     4,416    23,936      2,931.1  void k_check_rebuild_coords_and_box_gather<float>(int, const unsigned int *, const double *, const …
      1.6       33,379,313      4,000    8,344.8    8,224.0     7,360    35,904        610.8  void k_update_forward_baoab<float, (int)3>(int, T1, const unsigned int *, const T1 *, const T1 *, c…
      1.3       26,764,391      4,160    6,433.7    6,368.0     4,640    13,440        665.8  void k_gather_coords_and_params<double, (int)3, (int)4>(int, const unsigned int *, const T1 *, cons…
      1.0       21,400,038      4,000    5,350.0    5,312.0     4,256    15,104        491.8  void k_scatter_accum<unsigned long long, (int)3>(int, const unsigned int *, const T1 *, T1 *)       
      0.6       11,976,481        785   15,256.7   15,328.0    12,608    24,256        958.5  k_compact_trim_atoms(int, int, unsigned int *, unsigned int *, int *, unsigned int *)               
      0.4        7,356,492      1,120    6,568.3    5,455.5     3,167    17,408      3,537.3  void k_accumulate_energy<(unsigned int)512>(int, const __int128 *, __int128 *)                      
      0.3        6,498,456        400   16,246.1   16,160.0    14,049    17,536        385.2  void gen_sequenced<curandStateXORWOW, float2, normal_args_st, &curand_normal_scaled2<curandStateXOR…
      0.3        6,008,531        785    7,654.2    7,616.0     6,721    11,456        251.8  void k_find_block_bounds<float>(int, int, const unsigned int *, const double *, const double *, T1 …
      0.1        2,304,832        168   13,719.2   13,584.0    10,945    16,672      1,109.8  void cub::DeviceRadixSortOnesweepKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int>…
      0.0          729,437         80    9,118.0   10,016.0     6,688    10,656      1,376.0  void k_decide_move<float>(int, bool, int, double, double, const T1 *, T1 *, double *, const __int12…
      0.0          677,247         42   16,124.9   16,000.0     6,304    22,464      3,780.4  k_coords_to_kv_gather(int, const unsigned int *, const double *, const double *, const unsigned int…
      0.0          667,585         80    8,344.8    8,320.0     7,360     8,992        249.1  void k_find_group_centroids<float>(int, const double *, const int *, const int *, unsigned long lon…
      0.0          585,920         80    7,324.0    7,328.0     6,528     7,744        169.3  void k_rescale_positions<float>(int, double *, const T1 *, const double *, double *, const int *, c…
      0.0          429,534          3  143,178.0  137,119.0   136,704   155,711     10,855.9  void generate_seed_pseudo<rng_config<curandStateXORWOW, (curandOrdering)101>>(unsigned long long, u…
      0.0          208,507         80    2,606.3    2,560.0     2,464     3,072        114.5  void k_setup_barostat_move<float>(bool, const T1 *, double *, T1 *, double *, T1 *)                 
      0.0          195,133         42    4,646.0    4,480.0     3,808     6,976        509.5  void cub::DeviceRadixSortHistogramKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, int…
      0.0          111,934         42    2,665.1    2,624.0     2,048     3,008        228.2  void cub::DeviceRadixSortExclusiveSumKernel<cub::DeviceRadixSortPolicy<unsigned int, unsigned int, …
      0.0           17,823          8    2,227.9    2,255.5     1,759     2,688        291.4  k_arange(int, unsigned int *, unsigned int)                                                         
      0.0            2,144          1    2,144.0    2,144.0     2,144     2,144          0.0  void gen_sequenced<curandStateXORWOW, float, int, &curand_uniform_noargs<curandStateXORWOW>, rng_co…
```

### CODE REVIEW

**Comment by proteneer** [comment]
Does this still generating the actual noise in 64bit? (not sure if the rng bits were changed in this)

**Comment by badisa** [comment]
> Does this still generate the actual noise in 64bit? (not sure if the rng bits were changed in this)

The RNG bits were changed, they call this overloaded function (https://github.com/proteneer/timemachine/blob/master/timemachine/cpp/src/gpu_utils.cu#L5-L12) that will switch between generating noise using doubles/floats

**Comment by proteneer** [comment]
ah right, thanks - I forgot the rng was already overloaded.

**Comment by badisa** [comment]
> ah right, thanks - I forgot the rng was already overloaded.

Added kernel stats in the description for posterity to show the difference. Goes from 5% of the time is spent on generating noise to 0.3% of the time.

**Review by proteneer — APPROVED** [review]
lgtm!

**Review by mcwitt — APPROVED** [review]

**Pull request merged**
